# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-05 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rater_ip', models.CharField(max_length=15)),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Picture')),
            ],
        ),
        migrations.CreateModel(
            name='Fearful',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rater_ip', models.CharField(max_length=15)),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Picture')),
            ],
        ),
        migrations.CreateModel(
            name='Laughing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rater_ip', models.CharField(max_length=15)),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Picture')),
            ],
        ),
    ]
